# Generated by Django 4.2.3 on 2023-10-14 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('antman', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='private_key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
