# Generated by Django 4.2.3 on 2023-10-14 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('antman', '0002_userprofile_private_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivateKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
